### ISSUE TITLE
Problem with the page logo in dark mode

### ISSUE THREAD

**Issue by S3JER** [supercomputer-klubben-aau/sbcc-site#19]
The page logo's size in dark mode do not match the size of the logo in white mode. Because of this when switching between the modes the webpage shifts up and down.
![image](https://user-images.githubusercontent.com/72788875/222157158-46a4ef3c-43d0-432d-9696-3daded7bc343.png)

![image](https://user-images.githubusercontent.com/72788875/222157229-ed9ae190-4bb9-425d-9f50-fcd0491402c2.png)

**Comment by AndersSpringborg** [comment]
#2

**Comment by AndersSpringborg** [comment]
#18
